title: Tom Monck Jr
subtitle:
email: tom@monck.info
phone: Contact me via email for my phone number.
street_address: Contact me via email for my address.
github_url: https://github.com/tmonck
linkedin_url: https://www.linkedin.com/in/thomas-monck-jr
markdown: kramdown
include:
  - _pages
sass:
  sass_dir: _sass
url: https://tom.monck.info
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
